#:schema node_modules/wrangler/config-schema.json
name = "recovery-site"
main = "src/worker/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

route = { pattern = "recovery.evanpurkhiser.com", custom_domain = true }

[vars]
USERNAME = "evan"
TELEGRAM_CHAT_ID = "-722956237"
